version: '3.8'
services:
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: leo
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: nestdb
    ports:
      - "5433:5432"
    
volumes:
  postgres_data: